num1=int(input("Enter num1:"))
num2=int(input("Enter num2:"))
num3=int(input("Enter num3:"))
num4=int(input("Enter num4:"))
num5=int(input("Enter num5:"))
num6=int(input("Enter num6:"))
num7=int(input("Enter num7:"))
num8=int(input("Enter num8:"))
nums=num1,num2,num3,num4,num5,num6,num7,num8
res=set(nums)
print(res)
